### ISSUE TITLE
Splitting the project apart

### ISSUE THREAD

**Issue by ekampp** [Whiplash450/heresycreator#2]
We should consider splitting the project's javascript files into multiple files, so it's easier to debug a single feature, as well as add additional functionality to a feature. 

Ultimately, I see the skills javascript in a single file, stat picker in another, and so on. 

This way, new features, such as the talent picker can be an enclosed project, which can be tested independently of the other features. 

It will also allow me to more easily understand your thoughts and logic in each individual section of the generator. 

Let  me know your thoughts.

**Comment by Whiplash450** [comment]
I would agree, but I would much rather move the data to mySQL. Having it hardcoded in JS has been a major pain tbh. If it is broken down into relational tables should give you/us the same level of clear overview whilst keeping it easy to extend/manage/alter/update the data.

**Comment by ekampp** [comment]
I agree. Please make an issue moving the data to MySQL, and refer this one (see this [guide](https://help.github.com/articles/autolinked-references-and-urls))

We should still split the JS and the related HTML files. 

Ultimately, we should consider a frontend application such as Angular to replace jQuery. But that's down the road 😉
